modLoader = "javafml"
loaderVersion = "[21,)"
license = "MIT License"

[[mods]]
modId = "fightorflight"
version = "0.7.0"
displayName = "Cobblemon Fight or Flight"
authors = "rufia,LyquidQrystal"
description = '''
Makes Cobblemon run away or fight back in response to a player attack or failed capture
'''

[[dependencies.fightorflight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.fightorflight]]
modId = "neoforge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fightorflight]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"
